// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef FastFenGui_h
#define FastFenGui_h
#include <FL/Fl.H>
#include "chessView.h"
#include <FL/Fl_Double_Window.H>

class FastFenGui {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *mainWindow;
  ChessView *chessView;
};
#endif
